(()=>{const $=id=>document.getElementById(id),start=$('startButton'),restart=$('restartButton'),restart2=$('restartMiniButton'),left=$('leftButton'),right=$('rightButton'),boost=$('boostButton'),title=$('titleScreen'),game=$('gameScreen'),wrap=$('canvasWrap'),rankEl=$('rank'),distEl=$('distance'),speedEl=$('speed'),fill=$('boostFill'),msg=$('floatingMessage'),over=$('gameOverPanel'),resultTitle=$('resultTitle'),resultText=$('resultText');
let scene,camera,renderer,clock,player,started=false,running=false,progress=0,offset=0,target=0,speed=22,gauge=100,boostTime=0,cool=0,timer=0;
const FINISH=1800,road=[],markers=[],pads=[],ais=[],keys={l:false,r:false};
function center(p){return Math.sin(p/115)*2.8+Math.sin(p/42)*.75}function angle(p){return Math.atan2(center(p+1)-center(p-1),2)}
start.onclick=()=>{title.classList.add('hidden');game.classList.remove('hidden');if(!started){init();started=true}reset()};restart.onclick=restart2.onclick=reset;boost.onclick=doBoost;
function hold(b,k){b.onpointerdown=e=>{e.preventDefault();keys[k]=true};b.onpointerup=b.onpointerleave=b.onpointercancel=()=>keys[k]=false}hold(left,'l');hold(right,'r');
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a'){keys.l=true;e.preventDefault()}if(k==='arrowright'||k==='d'){keys.r=true;e.preventDefault()}if(k===' '){doBoost();e.preventDefault()}});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a')keys.l=false;if(k==='arrowright'||k==='d')keys.r=false});
function init(){scene=new THREE.Scene();scene.fog=new THREE.Fog(0xd9f5ff,28,105);camera=new THREE.PerspectiveCamera(48,wrap.clientWidth/wrap.clientHeight,.1,180);camera.position.set(0,2.8,10.8);camera.lookAt(0,.2,-12);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setSize(wrap.clientWidth,wrap.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;wrap.prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x6f9d52,1.55));const sun=new THREE.DirectionalLight(0xffffff,1.2);sun.position.set(8,14,8);scene.add(sun);makeRoad();player=kart(0xf04a3b,true);player.position.set(0,0,5);scene.add(player);makeAI();makePads();clock=new THREE.Clock();addEventListener('resize',resize);animate()}
function makeRoad(){const rm=new THREE.MeshStandardMaterial({color:0x52575f,roughness:.95}),gm=new THREE.MeshStandardMaterial({color:0x75bd50,roughness:1}),wm=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.9});for(let i=0;i<7;i++){const g=new THREE.Group(),grass=new THREE.Mesh(new THREE.PlaneGeometry(38,24),gm),r=new THREE.Mesh(new THREE.PlaneGeometry(11,24),rm);grass.rotation.x=r.rotation.x=-Math.PI/2;grass.position.y=-1.4;r.position.y=-1.34;g.add(grass,r);const l=new THREE.Mesh(new THREE.BoxGeometry(.18,.04,24),wm);l.position.set(-5.4,-1.29,0);const rr=l.clone();rr.position.x=5.4;g.add(l,rr);scene.add(g);road.push(g)}for(let i=0;i<40;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.18,.025,2.5),wm);m.position.y=-1.27;scene.add(m);markers.push({m,o:i*5})}}
function kart(color,isPlayer){const g=new THREE.Group(),bm=new THREE.MeshStandardMaterial({color,roughness:.82}),dm=new THREE.MeshStandardMaterial({color:0x30363d}),wm=new THREE.MeshStandardMaterial({color:0x171717});const base=new THREE.Mesh(new THREE.BoxGeometry(2.5,.38,3.2),bm);base.position.y=-.74;g.add(base);const seat=new THREE.Mesh(new THREE.BoxGeometry(1.1,.8,.2),dm);seat.position.set(0,0,-.55);g.add(seat);const wg=new THREE.CylinderGeometry(.36,.36,.32,18);[[-1.3,-.94,.95],[1.3,-.94,.95],[-1.3,-.94,-1.05],[1.3,-.94,-1.05]].forEach(p=>{const w=new THREE.Mesh(wg,wm);w.rotation.z=Math.PI/2;w.position.set(...p);g.add(w)});const d=isPlayer?mikan():aiHead();d.position.set(0,-.25,-.05);d.scale.setScalar(isPlayer?.66:.58);g.add(d);return g}
function mikan(){const g=new THREE.Group(),orange=new THREE.MeshStandardMaterial({color:0xff8c20}),lime=new THREE.MeshStandardMaterial({color:0xb7eb65}),green=new THREE.MeshStandardMaterial({color:0x35ad48}),red=new THREE.MeshStandardMaterial({color:0xe74437});const h=new THREE.Mesh(new THREE.SphereGeometry(.95,28,28),orange);h.position.set(0,1.35,.1);g.add(h);const b=new THREE.Mesh(new THREE.BoxGeometry(1.15,.95,.8),lime);b.position.y=.28;g.add(b);const c=new THREE.Mesh(new THREE.BoxGeometry(1.35,1,.07),red);c.position.set(0,.3,-.44);g.add(c);const l=new THREE.Mesh(new THREE.ConeGeometry(.1,.42,5),green);l.position.set(-.12,2.27,.05);l.rotation.z=-.35;const l2=l.clone();l2.position.x=.12;l2.rotation.z=.55;g.add(l,l2);const face=new THREE.Mesh(new THREE.PlaneGeometry(1.38,1.38),new THREE.MeshBasicMaterial({map:faceTex(),transparent:true}));face.position.set(0,1.35,.93);g.add(face);const mm=new THREE.Mesh(new THREE.PlaneGeometry(.78,.7),new THREE.MeshBasicMaterial({map:mTex(),transparent:true}));mm.position.set(0,.28,.42);g.add(mm);return g}
function aiHead(){const g=new THREE.Group(),cs=[0x5ec4ff,0xffd84d,0xb477ff],h=new THREE.Mesh(new THREE.SphereGeometry(.8,22,22),new THREE.MeshStandardMaterial({color:cs[Math.floor(Math.random()*3)]})),b=new THREE.Mesh(new THREE.BoxGeometry(1,.8,.7),new THREE.MeshStandardMaterial({color:0xffffff}));h.position.y=1.1;b.position.y=.25;g.add(h,b);return g}
function makeAI(){[0x4c8dff,0xffcf33,0xa968ff].forEach((c,i)=>{const k=kart(c,false);scene.add(k);ais.push({k,p:12+i*5,v:21+i*.6,l:[-2.2,0,2.2][i],w:Math.random()*6.28})})}
function makePads(){[150,330,520,720,930,1160,1380,1580].forEach((p,i)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(3.3,.05,3.6),new THREE.MeshStandardMaterial({color:0x24cfff,emissive:0x0a5c72,emissiveIntensity:.7}));m.position.y=-1.24;scene.add(m);pads.push({m,p,l:[-2.2,0,2.2][i%3],u:false})})}
function reset(){progress=0;offset=target=0;speed=22;gauge=100;boostTime=cool=0;keys.l=keys.r=false;over.classList.add('hidden');ais.forEach((a,i)=>{a.p=12+i*5;a.v=21+i*.6+Math.random()*.5});pads.forEach(p=>p.u=false);running=true;if(clock)clock.getDelta();show('GO!');hud()}
function doBoost(){if(!running||gauge<25||cool>0)return;gauge-=25;boostTime=Math.max(boostTime,1.2);cool=.35;show('BOOST!')}
function update(dt){if(keys.l)target-=6.5*dt;if(keys.r)target+=6.5*dt;target=Math.max(-3.5,Math.min(3.5,target));offset+=(target-offset)*Math.min(1,9*dt);if(cool>0)cool-=dt;if(boostTime>0)boostTime-=dt;else gauge=Math.min(100,gauge+7*dt);speed=Math.max(15,22+(boostTime>0?11:0)-Math.abs(angle(progress))*18);progress+=speed*dt;ais.forEach(a=>{const rv=(progress-a.p)*.012;a.p+=Math.max(17.5,a.v+rv-Math.abs(angle(a.p))*8+Math.sin(a.p*.015+a.w)*.35)*dt;const z=5-(a.p-progress),x=center(a.p)-center(progress)+a.l;a.k.position.set(x,0,z);a.k.rotation.y=-angle(a.p);a.k.visible=z>-70&&z<14});world();checkPads();hud();if(progress>=FINISH)finish()}
function world(){const c=center(progress);road.forEach((s,i)=>{const a=i*24-8,p=progress+a;s.position.z=8-a;s.position.x=center(p)-c;s.rotation.y=-angle(p)});markers.forEach(x=>{let r=(x.o-(progress%200)+200)%200;if(r>120)r-=200;const p=progress+r;x.m.position.z=8-r;x.m.position.x=center(p)-c;x.m.rotation.y=-angle(p);x.m.visible=r>-10&&r<105});pads.forEach(x=>{const r=x.p-progress;x.m.position.z=5-r;x.m.position.x=center(x.p)-c+x.l;x.m.rotation.y=-angle(x.p);x.m.visible=r>-8&&r<105&&!x.u});player.position.x=offset;player.rotation.y=-angle(progress)*.75;camera.position.x+=(offset*.2-camera.position.x)*.08;camera.lookAt(offset*.1,.15,-13)}
function checkPads(){pads.forEach(x=>{if(!x.u&&Math.abs(x.p-progress)<1.5&&Math.abs(offset-x.l)<1.7){x.u=true;boostTime=Math.max(boostTime,1.65);gauge=Math.min(100,gauge+20);show('PAD BOOST!')}})}
function hud(){const a=[{n:'p',p:progress},...ais.map((x,i)=>({n:'a'+i,p:x.p}))].sort((x,y)=>y.p-x.p),r=a.findIndex(x=>x.n==='p')+1;rankEl.textContent=r+'/4';distEl.textContent=Math.min(FINISH,Math.floor(progress))+'m';speedEl.textContent=Math.round(speed*7);fill.style.width=gauge+'%'}
function finish(){running=false;const a=[{n:'p',p:progress},...ais.map((x,i)=>({n:'a'+i,p:x.p}))].sort((x,y)=>y.p-x.p),r=a.findIndex(x=>x.n==='p')+1;resultTitle.textContent=r===1?'1位！':r+'位でゴール！';resultText.textContent='AIカート3台とのレース結果：'+r+' / 4';over.classList.remove('hidden')}
function faceTex(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle='#161616';x.beginPath();x.arc(180,180,34,0,Math.PI*2);x.fill();x.beginPath();x.arc(330,180,34,0,Math.PI*2);x.fill();x.strokeStyle='#161616';x.lineWidth=18;x.beginPath();x.moveTo(248,245);x.lineTo(316,256);x.lineTo(252,404);x.lineTo(208,278);x.closePath();x.stroke();return new THREE.CanvasTexture(c)}
function mTex(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.strokeStyle='#fff';x.lineWidth=44;x.lineCap='round';x.lineJoin='round';x.beginPath();x.moveTo(90,395);x.lineTo(90,125);x.lineTo(188,260);x.lineTo(256,178);x.lineTo(324,260);x.lineTo(422,125);x.lineTo(422,395);x.stroke();return new THREE.CanvasTexture(c)}
function show(t){msg.textContent=t;msg.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>msg.classList.remove('show'),700)}
function resize(){const w=wrap.clientWidth,h=wrap.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033);if(running)update(dt);renderer.render(scene,camera)}})();